add phala into web3 subgraph
web3index/subgraph pull request #2
Opened 2021-09-16 09:23 UTC by tolak

2021-09-24 09:12 UTC, shreyaspapi requested changes
I had to do few changes for the build to work, still the subgraph has failed indexing. I have added few comments I think it might help. Also @adamsoffer has to check it.

2021-09-24 09:12 UTC, shreyaspapi commented on src/phala/mapping.ts
> +import { Transfer } from "../types/phala/Transfer";
```suggestion
import { Transfer } from "../types/phala/PHA";
```

2021-09-24 09:12 UTC, shreyaspapi commented on src/phala/mapping.ts
> +  let amount = convertToDecimal(event.params.amount);
```suggestion
  let amount = convertToDecimal(event.params.value);
```

2021-09-24 09:12 UTC, shreyaspapi commented on subgraph.yaml
> +        - event: Transfer(indexed address,indexed address,indexed uint256)
```suggestion
        - event: Transfer(indexed address,indexed address,uint256)
```

2021-09-24 09:12 UTC, shreyaspapi commented on src/phala/mapping.ts
> +  let amount = convertToDecimal(event.params.amount);
I had to do this change to make the build work, as the event don't include amount.

2021-09-24 09:12 UTC, shreyaspapi commented on subgraph.yaml
> +        - event: Transfer(indexed address,indexed address,indexed uint256)
There is no event in PHA.json which corresponds to `Transfer(indexed address,indexed address,indexed uint256)`.

2021-09-24 09:33 UTC, tolak commented
@shreyaspapi Thanks for your feed back, already fixed the issues above.

2021-10-18 14:50 UTC, shelvenzhou commented
@shreyaspapi Hello. We have fixed the issues. Could you check if this is ready to merge? Thank you.

2021-10-18 14:56 UTC, shreyaspapi commented
> I had to do few changes for the build to work, still the subgraph has failed indexing.

Hey @shelvenzhou As I mentioned previously the changes were only meant for the build to pass, there are still issues that need to be fixed for the graph to index it.

2025-11-17 15:28 UTC, rickstaa commented
@shreyaspapi closed since this is an old PR. Feel free reopen a new one for the decentralised subgraph. Thanks!

2025-11-17 15:28 UTC, closed without merging